# Basic App Properties
app.name=My Super Spring App
app.version=2.5.3

app.message=This is from Properties file

# Grouped Server Properties
server.connection.timeout=5000
server.connection.host=localhost
server.connection.max-users=100