package com.learning.spring.data;


import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import java.util.Optional;

public class MainApp {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext context =
                new AnnotationConfigApplicationContext(AppConfig.class);

        // Get the Proxy implementation generated by Spring Data
        UserRepository userRepo = context.getBean(UserRepository.class);

        System.out.println("Saving users...");
        // 1. save() is provided automatically by JpaRepository
        userRepo.save(new User("john_doe", "secret123"));
        userRepo.save(new User("jane_smith", "admin456"));

        System.out.println("\n--- Find All ---");
        // 2. findAll() is provided automatically
        userRepo.findAll().forEach(System.out::println);

        System.out.println("\n--- Find By ID ---");
        // 3. findById returns an Optional<User>
        Optional<User> user = userRepo.findById("john_doe");
        user.ifPresent(System.out::println);

        System.out.println("\n--- Custom Generated Method (Find By Password) ---");
        // 4. Our custom method interface definition
        User specialUser = userRepo.findByPassword("admin456");
        System.out.println(specialUser);

        context.close();
    }
}
